trigger:
- main

variables:
  terraformVersion: '1.6.6'

stages:
- stage: DEV
  displayName: Deploy DEV
  jobs:
  - job: TerraformDEV
    pool:
      vmImage: ubuntu-latest
    steps:
    - checkout: self

    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@1
      inputs:
        terraformVersion: $(terraformVersion)

    - task: TerraformTaskV4@4
      displayName: Terraform Init DEV
      inputs:
        provider: azurerm
        command: init
        workingDirectory: env/dev
        backendServiceArm: azurerm-connection
        backendAzureRmResourceGroupName: rg-tfstate
        backendAzureRmStorageAccountName: moathtfstate123
        backendAzureRmContainerName: tfstate
        backendAzureRmKey: dev.terraform.tfstate

    - task: TerraformTaskV4@4
      displayName: Terraform Plan DEV
      inputs:
        provider: azurerm
        command: plan
        workingDirectory: env/dev
        environmentServiceNameAzureRM: azurerm-connection

    - task: TerraformTaskV4@4
      displayName: Terraform Apply DEV
      inputs:
        provider: azurerm
        command: apply
        workingDirectory: env/dev
        environmentServiceNameAzureRM: azurerm-connection

- stage: PROD
  displayName: Deploy PROD
  dependsOn: DEV
  jobs:
  - job: TerraformPROD
    pool:
      vmImage: ubuntu-latest
    steps:
    - checkout: self

    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@1
      inputs:
        terraformVersion: $(terraformVersion)

    - task: TerraformTaskV4@4
      displayName: Terraform Init PROD
      inputs:
        provider: azurerm
        command: init
        workingDirectory: env/prod
        backendServiceArm: azurerm-connection
        backendAzureRmResourceGroupName: rg-tfstate
        backendAzureRmStorageAccountName: moathtfstate123
        backendAzureRmContainerName: tfstate
        backendAzureRmKey: prod.terraform.tfstate

    - task: TerraformTaskV4@4
      displayName: Terraform Plan PROD
      inputs:
        provider: azurerm
        command: plan
        workingDirectory: env/prod
        environmentServiceNameAzureRM: azurerm-connection

    - task: TerraformTaskV4@4
      displayName: Terraform Apply PROD
      inputs:
        provider: azurerm
        command: apply
        workingDirectory: env/prod
        environmentServiceNameAzureRM: azurerm-connection
