trigger:
- main

variables:
  terraformVersion: '1.6.6'

stages:
# ==================================================
# DEV STAGE
# ==================================================
- stage: DEV
  displayName: Deploy DEV
  jobs:
  - job: TerraformDEV
    displayName: Terraform DEV
    pool:
      vmImage: ubuntu-latest

    steps:
    - checkout: self

    # Install Terraform
    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@1
      displayName: Install Terraform
      inputs:
        terraformVersion: $(terraformVersion)

    # Terraform INIT (DEV)
    - task: TerraformTaskV4@4
      displayName: Terraform Init DEV
      inputs:
        provider: azurerm
        command: init
        commandOptions: '-reconfigure'
        workingDirectory: env/dev
        backendServiceArm: moath-sp-new
        backendAzureRmResourceGroupName: rg-tfstate
        backendAzureRmStorageAccountName: moathtfstate123
        backendAzureRmContainerName: tfstate
        backendAzureRmKey: dev.terraform.tfstate

    # Terraform PLAN (DEV)
    - task: TerraformTaskV4@4
      displayName: Terraform Plan DEV
      inputs:
        provider: azurerm
        command: plan
        commandOptions: '-input=false'
        workingDirectory: env/dev
        environmentServiceNameAzureRM: moath-sp-new
        vars: |
          admin_password=$(admin_password)

    # Terraform APPLY (DEV)
    - task: TerraformTaskV4@4
      displayName: Terraform Apply DEV
      inputs:
        provider: azurerm
        command: apply
        commandOptions: '-input=false -auto-approve'
        workingDirectory: env/dev
        environmentServiceNameAzureRM: moath-sp-new
        vars: |
          admin_password=$(admin_password)

# ==================================================
# PROD STAGE
# ==================================================
- stage: PROD
  displayName: Deploy PROD
  dependsOn: DEV
  condition: succeeded()
  jobs:
  - job: TerraformPROD
    displayName: Terraform PROD
    pool:
      vmImage: ubuntu-latest

    steps:
    - checkout: self

    # Install Terraform
    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@1
      displayName: Install Terraform
      inputs:
        terraformVersion: $(terraformVersion)

    # Terraform INIT (PROD)
    - task: TerraformTaskV4@4
      displayName: Terraform Init PROD
      inputs:
        provider: azurerm
        command: init
        commandOptions: '-reconfigure'
        workingDirectory: env/prod
        backendServiceArm: moath-sp-new
        backendAzureRmResourceGroupName: rg-tfstate
        backendAzureRmStorageAccountName: moathtfstate123
        backendAzureRmContainerName: tfstate
        backendAzureRmKey: prod.terraform.tfstate

    # Terraform PLAN (PROD)
    - task: TerraformTaskV4@4
      displayName: Terraform Plan PROD
      inputs:
        provider: azurerm
        command: plan
        commandOptions: '-input=false'
        workingDirectory: env/prod
        environmentServiceNameAzureRM: moath-sp-new
        vars: |
          admin_password=$(admin_password)

    # Terraform APPLY (PROD)
    - task: TerraformTaskV4@4
      displayName: Terraform Apply PROD
      inputs:
        provider: azurerm
        command: apply
        commandOptions: '-input=false -auto-approve'
        workingDirectory: env/prod
        environmentServiceNameAzureRM: moath-sp-new
        vars: |
          admin_password=$(admin_password)
